import Navbar from "@/components/navbar";
import { config } from "@/config";
import { Web3Modal } from "@/context";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialState = cookieToInitialState(config, headers().get("cookie"));
    return (
        <html lang="en" className="bg-black">
            <body
                className={cn(
                    "w-full h-screen flex flex-row items-center justify-center",
                    inter.className
                )}>
                <Web3Modal initialState={initialState}>
                    <Navbar />
                    {children}
                </Web3Modal>
            </body>
        </html>
    );
}
